alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: chabanov/stels-func
  name: stels-func
  routes:
  - path: /
  source_dir: /
name: stels